bugfix: Autohelp
devcordde/DevcordBot pull request #123
Opened 2020-08-27 20:56 UTC by DRSchlaubi

- Ignore whitespaces in exception names
- Allow modifiers behind class name (extends, implements) (#113)
- Fix bug in class name parsing
- Ignore if caused by is prefix by something like `Caused by in exception
- Update to Kotlin 1.4
- Update to Gradle 6.6
- Make tag names case insensitive (#105)
- Remove un-permitted reactions in rat-chat (#122)
- Fix to long raw tags causing exception (#119)

### Github
Fixes #113 
Fixes #105 
Fixes #122 
Fixes #119

2020-08-27 21:32 UTC, jkoenig134 requested changes

2020-08-27 21:32 UTC, jkoenig134 commented on src/main/kotlin/com/github/devcordde/devcordbot/core/RatProtector.kt
> +        if (event.user?.isBot == true || event.channel.idLong != channelId || event.member?.roles?.any { it.idLong == roleId } == true) return
A team member should be able to react - not every team member has the "rat" role.

2020-08-27 22:04 UTC, jkoenig134 commented on src/main/kotlin/com/github/devcordde/devcordbot/core/RatProtector.kt
> +}
newline

2020-08-28 16:48 UTC, DRSchlaubi commented on src/main/kotlin/com/github/devcordde/devcordbot/core/RatProtector.kt
> +}
ragequit

2020-08-28 16:51 UTC, jkoenig134 approved these changes
LGTM

2020-08-28 17:08 UTC, Seliba approved these changes

2020-08-28 17:52 UTC, merged