Enable guild caching
devcordde/DevcordBot pull request #206
Opened 2021-06-05 21:31 UTC by dlsf

This will (hopefully) solve the issue that the member count is null on /info

2021-06-05 21:40 UTC, DRSchlaubi commented
This sounds like a bad idea

2021-06-05 21:47 UTC, DRSchlaubi requested changes
```suggestion
implementation("dev.kord", "kord-core", "0.7.x-SNAPSHOT")
```

Need to change this too or you will get issues with ktor 1.6

2021-06-05 21:55 UTC, DRSchlaubi commented
The problem here isn't that the Guild cache isn't enabled. It's that you try to fetch the guild before the ready event get's fired so the guild can't be cached yet and has to be resolved through rest.
so best way of handeling this would probabbly be to fetch the guild each time you need it

The guild cache is enabled per default and this shouldn't change anything

Also let's poke @BartArys to fix: https://github.com/kordlib/kord/issues/55

2021-06-05 21:56 UTC, dlsf commented
Thanks for the clarification

2021-08-03 23:48 UTC, DRSchlaubi commented on src/main/kotlin/com/github/devcordde/devcordbot/Launcher.kt
> +        }
This still won't have any effect since guild caching is a thing that is enabled by default

2021-08-15 21:27 UTC, DRSchlaubi commented
This PR will be superseded buy an upcoming PR

2021-08-22 11:29 UTC, closed without merging