Fix bugs because no one else fixes them
devcordde/DevcordBot pull request #209
Opened 2021-08-15 22:17 UTC by DRSchlaubi

- Optimize tag Database queries - Also query alias for auto-help tags - Increase tag column size since the message limit doesn't account for Markdown
- Make use of ephemeral commands - Make autohelp find casting tag properly - Fix tag finding
- Add BOM module gradle file
- Bump dependencies
- Fix dependency upgrade issues
- Cleanup code
- Add ability to delete command responses Co-authored-by: amejonah1200 <amejonah@gmail.com>
- Update dependencies
- Fetch Bot Guild correctly (Fix #205)
- Add user avatar to /rank stats (Fix #204)
- Use components for paginator (Fix #158)
- Add logs to make das_ happy
- Update merge-in for new changes

2021-08-15 22:19 UTC, DRSchlaubi commented
This also superseeds #206 and #203

2021-08-28 18:06 UTC, JohnnyJayJay submitted a review, later dismissed

2021-09-16 12:01 UTC, dlsf requested changes

2021-09-16 12:01 UTC, daspositioned commented on src/main/kotlin/com/github/devcordde/devcordbot/command/AbstractCommand.kt
> +import com.github.devcordde.devcordbot.command.root.AbstractSingleCommand
I'm pretty sure these imports are not needed
```suggestion
```

2021-09-16 12:05 UTC, DRSchlaubi commented on src/main/kotlin/com/github/devcordde/devcordbot/command/AbstractCommand.kt
> +import com.github.devcordde.devcordbot.command.root.AbstractSingleCommand
If they weren't needed the Klimt check should have failed

2021-09-16 12:08 UTC, dlsf commented on src/main/kotlin/com/github/devcordde/devcordbot/command/AbstractCommand.kt
> +import com.github.devcordde.devcordbot.command.root.AbstractSingleCommand
But you didn't add anything to that class besides these imports. Am I missing something here?

2021-09-16 12:24 UTC, DRSchlaubi commented on src/main/kotlin/com/github/devcordde/devcordbot/command/AbstractCommand.kt
> +import com.github.devcordde.devcordbot.command.root.AbstractSingleCommand
These are not unused, they're used in the doc comment

2021-09-16 13:38 UTC, dlsf approved these changes

2021-09-16 14:17 UTC, merged