Add rank cleanup command
devcordde/DevcordBot pull request #55
Opened 2020-06-18 20:02 UTC by Seliba

2020-06-18 20:38 UTC, jkoenig134 requested changes

2020-06-18 20:38 UTC, jkoenig134 commented on src/main/kotlin/com/github/devcordde/devcordbot/commands/owners/CleanupCommand.kt
> +}
you know

2020-06-18 20:39 UTC, jkoenig134 approved these changes

2020-06-18 21:02 UTC, jkoenig134 approved these changes

2020-06-18 21:30 UTC, DRSchlaubi requested changes

2020-06-18 21:32 UTC, DRSchlaubi commented on src/main/kotlin/com/github/devcordde/devcordbot/commands/general/TagCommand.kt
> +                    context.jda.getGuildById(dotenv()["GUILD_ID"] ?: return@forEach)?.retrieveMemberById(it.userID)
Also retrieving members 6k times will probably get us ratelimited

2020-06-18 21:33 UTC, jkoenig134 commented on src/main/kotlin/com/github/devcordde/devcordbot/commands/general/TagCommand.kt
> +                    context.jda.getGuildById(dotenv()["GUILD_ID"] ?: return@forEach)?.retrieveMemberById(it.userID)
In that point we shouldn´t use the cache. We want to see the really *current* status of the member.

2020-06-18 21:41 UTC, DRSchlaubi commented on src/main/kotlin/com/github/devcordde/devcordbot/commands/general/TagCommand.kt
> +                    context.jda.getGuildById(dotenv()["GUILD_ID"] ?: return@forEach)?.retrieveMemberById(it.userID)
Using retrieve doesn help with that, cache is based on Gateway Events so the cache should be pretty up to date

Also we're just filtering if the member left so retrieving doesn't really help

Also also we,re retrieving member data twice per membe, dk about exact date limit in retrievemember but it's probably not intended to be called 4k Times within a few minutes

2020-06-19 06:26 UTC, jkoenig134 approved these changes

2020-06-19 07:18 UTC, DRSchlaubi approved these changes
LGTM

2020-06-19 07:22 UTC, jkoenig134 approved these changes

2020-06-19 11:56 UTC, merged